In [1]:
import numpy as np

In [2]:
array1 = np.array(range(30))

In [3]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
array1.reshape((5, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [5]:
array1 = np.array(array1, order="F")

In [6]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
np.array(array1, order="F")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
array1.reshape((5, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [9]:
array1 = np.where(%6 == 1)

SyntaxError: invalid syntax (<ipython-input-9-eb908f2100dc>, line 1)

In [10]:
array1 = np.where(/6 == 1)

SyntaxError: invalid syntax (<ipython-input-10-4c279aeb9f4b>, line 1)

In [11]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
array1 = np.where((%6) == 1)

SyntaxError: invalid syntax (<ipython-input-12-aad4866cd174>, line 1)

In [13]:
np.where(array1%6 ==1)

(array([ 1,  7, 13, 19, 25], dtype=int64),)