In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,55,60])

chinese_score = np.array([65,90,82,72,66,77])

In [3]:
english_score - math_score

array([-5,  4, 16, -3, -7, 10])

In [4]:
result = np.array([-5,  4, 16, -3, -7, 10])

In [5]:
result[result>0]

array([ 4, 16, 10])

In [6]:
len(array([ 4, 16, 10]))

NameError: name 'array' is not defined

In [7]:
len(result[result>0])

3

In [8]:
#有多少學生英文成績比數學成績高？3位

In [9]:
chinese_score - math_score

array([ 5,  5, 22,  4, 11, 17])

In [10]:
chinese_score - english_score

array([10,  1,  6,  7, 18,  7])

In [11]:
#是否全班同學最高分都是國文？是